spring.application.name=Risk_Engane
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Risk-Engine
spring.datasource.username=postgres
spring.datasource.password=log3in7dat

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true